name: Tarabut CICD
on: 
  push
        
jobs:
  Build_Push_DockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: faraaz/tarabut:v1.0.0
          
#       - name: Slack Notification
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # - uses: jtalk/k8s-deploy@v2
      #   with:
      #     namespace: 'tarabut'
      #     manifests: |
      #         kubernetes/deployment.yaml
      #     kubectl-version: 'latest'
      #   env:
      #     KUBECONFIG: ${{secrets.KUBECONFIG}}
          
      # - name: Wait for pods
      #   uses: CodingNagger/minikube-wait-action@v1.0.1
      # - name: Check pods
      #   run: |
      #     kubectl get pods -n tarabut

      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"kubectl rollout status deployment/python-app-deployment -n tarabut"'
